service: cloudwatch-slack

plugins:
  - serverless-python-requirements

package:
  individually: true
  include:
    - '!./**'
    - './src/**'
  exclude:
    - '**'

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    invalidateCaches: true
    fileName: src/requirements.txt

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-southeast-2

functions:
  cloudwatch-slack:
    handler: src.lambda_function.lambda_handler
